### ISSUE TITLE
Incorrect type when importing different files as provider & functions

### ISSUE THREAD

**Issue by jung35** [lalcebo/json-schema#1]
I have a configuration in serverless.yml like below to split up my configuration
```
provider: ${file(./config/provider.yml)}

functions: ${file(./config/functions.yml)}
```

This schema is causing error on my vscode

<img width="738" alt="Screen Shot 2022-01-05 at 3 06 15 PM" src="https://user-images.githubusercontent.com/674062/148281900-89a0a2fa-132a-4fd5-a720-951a84f78a0e.png">

**Comment by lalcebo** [comment]
@jung35 I'm working on it, there will be an update soon.

Thanks.

**Comment by lalcebo** [comment]
Fix: https://github.com/lalcebo/json-schema/commit/68d34f284836f8865945a8707c26a1a24fa44411
