### ISSUE TITLE
AWS::AppSync::DomainName & AWS::AppSync::DomainNameApiAssociation

### ISSUE THREAD

**Issue by and3rson** [lalcebo/json-schema#15]
There are some new CFN resource types:

- `AWS::AppSync::DomainName`
- `AWS::AppSync::DomainNameApiAssociation`

Those are currently not known to your serverless schema. Is it possible to add them?

Thanks in advance!

**Comment by KillDozerX2** [comment]
PR ready, @lalcebo have a look if I missed anything.

**Comment by and3rson** [comment]
@KillDozerX2 Thank you for such a quick reaction!
