### ISSUE TITLE
Problems loading reference AwsStepFunctions parse error

### ISSUE THREAD

**Issue by mike-mlmedia** [lalcebo/json-schema#157]
Getting an error in VSCode:

Problems loading reference 'https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/plugin/step_functions.json#/AwsStepFunctions': Unable to parse content from 'https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/plugin/step_functions.json': Parse error at offset 38598.

Maybe related to this commit: https://github.com/lalcebo/json-schema/commit/64f1011f5a513513c2863711f00f77a28d295dcc

@marceliwac

**Comment by mike-mlmedia** [comment]
Looks like it's maybe a trailing comma syntax error on line 1559

**Comment by marceliwac** [comment]
Really sorry for this! I think this rogue comma must have sneaked up when I copied code from the editor during testing. Patch #158 should resolve this. @lalcebo

**Comment by mike-mlmedia** [comment]
Confirmed error message gone.  Thanks Marceli!
