### ISSUE TITLE
custom webpack scripts incorrect type definition

### ISSUE THREAD

**Issue by DarlonHenrique** [lalcebo/json-schema#174]
![image](https://github.com/lalcebo/json-schema/assets/67025443/3fc0f248-0289-4338-9b07-ec5c48f1c5cc)

the type inside the webpack plugin schema is saying its a boolean

 but the documentation say its a array

**Comment by lalcebo** [comment]
Resolved: https://github.com/lalcebo/json-schema/commit/aa2e9cbfefa4bc8a599e2f97664b24f29762c0ac
