### ISSUE TITLE
Feature request: Non-AWS specific schemas

### ISSUE THREAD

**Issue by neoromantique** [lalcebo/json-schema#18]
This schema is AWS specific would extending it to include other providers (ex. Scaleway Functions) be within scope of this project, or is out of scope? 

If so, it probably should be marked as such

Thanks

**Comment by neoromantique** [comment]
Okay, it took me a moment, but I figured out that other providers are actually working through a plugin and not directly with serverless framework, so this would be out of scope for this spec, sorry.

**Comment by KillDozerX2** [comment]
@neoromantique 
This schema already has support for step funding which comes through plugins, so we might be able to help since the goal of this schema is for serverless.
@lalcebo should we track this issue or not?

**Comment by neoromantique** [comment]
> @neoromantique This schema already has support for step funding which comes through plugins, so we might be able to help since the goal of this schema is for serverless. @lalcebo should we track this issue or not?

https://github.com/scaleway/serverless-scaleway-functions

This is the plugin in question, thank you

**Comment by KillDozerX2** [comment]
@neoromantique open api schema has an option for discriminator which allows schema to change based on the value of some property, but that's not supported here. What I'm suggesting is using different file names to use different schemas. So in your case we could create a separate schema that matches `serverless.scaleway.yml` and put that up on schema store. Would that be something that you'd be comfortable with?

**Comment by neoromantique** [comment]
> @neoromantique open api schema has an option for discriminator which allows schema to change based on the value of some property, but that's not supported here. What I'm suggesting is using different file names to use different schemas. So in your case we could create a separate schema that matches `serverless.scaleway.yml` and put that up on schema store. Would that be something that you'd be comfortable with?

Sounds good to me, thank you :)
