### ISSUE TITLE
Missing multiple definitions

### ISSUE THREAD

**Issue by shamsup** [lalcebo/json-schema#2]
see https://github.com/SchemaStore/schemastore/issues/2004

- Missing `AWS::CloudFront::CachePolicy` :heavy_check_mark: 
- Missing `AWS::ApiGatewayV2::Api`
- missing `BillingMode` on `AWS::DynamoDB::Table` :heavy_check_mark: 
- missing `DependsOn` for `AWS::Cloudfront::Distribution` :heavy_check_mark: 
- iamRoleStatements Resource does not allow cloudformation functions (ie Fn::Join) :heavy_check_mark:

**Comment by shamsup** [comment]
Adding to the list

- `UsernameConfiguration` property for `AWS::Cognito::UserPool`  ✔️
- `AWS::Cognito::UserPoolClient` properties
  - `AllowedOAuthFlowsUserPoolClient` ✔️
  - `AllowedOAuthFlows` ✔️
  - `AllowedOAuthScopes` ✔️
  - `LogoutURLs` ✔️
  - `CallbackURLs` ✔️
  - `SupportedIdentityProviders` ✔️
- `AWS::Cognito::UserPoolDomain` type ✔️
-  `AWS::Cognito::UserPoolUICustomizationAttachment` type ✔️

**Comment by lalcebo** [comment]
@shamsup I'll work on it, there will be an update soon. All contributions from the community are welcome.

Thanks.

**Comment by lalcebo** [comment]
The second group of missing items remains to be created.

**Comment by KillDozerX2** [comment]
@lalcebo and @shamsup All done now.
