### ISSUE TITLE
`DeletionPolicy` not defined in schema for cloudformation resources.

### ISSUE THREAD

**Issue by fuadop** [lalcebo/json-schema#30]
![Screenshot from 2022-06-27 12-08-01](https://user-images.githubusercontent.com/65264054/175928019-794ec8fe-55e2-4612-9bfc-931d474278c3.png)

I get an error in VSCode linting for DeletionPolicy. DeletionPolicy is a part of CloudFormation, and the resources section of the serverless.com configuration file (serverless.yml) should be purely CloudFormation. Please correct me if I'm wrong.

**Comment by KillDozerX2** [comment]
@fuadop released, closing this issue, please let me know if you're still facing this issue.

**Comment by fuadop** [comment]
Hey @KillDozerX2, 

Thanks for the quick help !. However I still get the error, is there some sort of caching on vscode? Do you have an idea of how I could trigger a refresh?

**Comment by KillDozerX2** [comment]
@fuadop open command pallete and search for `json: clear schema cache`
I've encountered multiple bugs with this issue, specially while developing this schema. The best resort is to clear the cache and then simply restart vscode.
<img width="632" alt="Screenshot 2022-07-01 at 9 03 19 PM" src="https://user-images.githubusercontent.com/29596786/176925359-ea0a7647-1e1d-4ed3-8578-158a58f0e430.png">
O
