### ISSUE TITLE
Add pattern for filename

### ISSUE THREAD

**Issue by KillDozerX2** [lalcebo/json-schema#33]
@c2karansingh Please have a look.
https://github.com/lalcebo/json-schema/blob/571eb058fefb4220e0582f173d49fa4fa10b3693/serverless/reference.json#L40856-L40859

It should look something like this:- ${file(.yml)}

**Comment by c2karansingh** [comment]
@KillDozerX2 See if [this](https://regexr.com/6p1r0) scratches the itch

**Comment by c2karansingh** [comment]
gimme a few samples in case it doesn't work for any example, your permalink doesn't open directly as the file is too big, going to line 40856 shows the following which doesn't seem like what you wanted to show me @KillDozerX2 
![image](https://user-images.githubusercontent.com/31315654/177159217-d4f1ccf0-c02e-44dc-9872-3b1b5be55f12.png)

**Comment by KillDozerX2** [comment]
> this

That's where you're supposed to add the pattern.

**Comment by KillDozerX2** [comment]
@c2karansingh seems to be working for me. Thanks.

**Comment by c2karansingh** [comment]
@KillDozerX2 where do you want me to use it?
