### ISSUE TITLE
package.patterns property

### ISSUE THREAD

**Issue by tamlyn** [lalcebo/json-schema#35]
[The packaging config](https://www.serverless.com/framework/docs/providers/aws/guide/packaging) has deprecated `include` and `exclude` properties in favour of a single `patterns` property.

The definition for `Aws.Package` is missing the new `patterns` prop. 

`include` and `exclude` still appear to work but they are undocumented so I don't know if it's best to leave them in the schema or remove them.

**Comment by KillDozerX2** [comment]
@tamlyn solved, also added deprecation notices for include and exclude.
