### ISSUE TITLE
Split `reference.json` on sub schemas.

### ISSUE THREAD

**Issue by lalcebo** [lalcebo/json-schema#79]
The `reference.json` file has become very large and difficult to maintain. We will split it into sub schemas to improve its maintainability.

Example:

![image](https://user-images.githubusercontent.com/16945969/206584852-96068458-ac4c-4df2-920a-79a5c76e557f.png)

**Comment by KillDozerX2** [comment]
Have made a lot of headway

**Comment by KillDozerX2** [comment]
@lalcebo we should close this issue now, I think we've finished this.
