### ISSUE TITLE
Multiple Properties are missing from Cognito User Pool

### ISSUE THREAD

**Issue by Darshanbc** [lalcebo/json-schema#8]
Multiple Properties are missing from Cognito User Pool
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-mfaconfiguration

**Comment by KillDozerX2** [comment]
@lalcebo @Darshanbc Should be good now.

**Comment by lalcebo** [comment]
Thanks, @KillDozerX2
